name: Build and deploy .NET 8 isolated Azure Function App - flatt-functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './flatt-functions'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and publish
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish --configuration Release --no-build --output ./output
          popd

      - name: Deploy to Azure Functions
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'flatt-functions' # your Function App name
          package: '${{ github.workspace }}/flatt-functions/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5B38BFBFB0914845B804A010991883CA }}
